package main

import (
	"encoding/json"
	"fmt"
	"strings"
	"text/template"
)

// NotebookParams are the values the panel bakes into the runner script.
type NotebookParams struct {
	KernelToken string
	TunnelToken string
	IdleSeconds int
	CapSeconds  int
	Runtime     string // dataset slug holding ComfyUI and cloudflared
	Models      []ModelMount
	Accelerator string
}

// ModelMount ties a mounted dataset to the ComfyUI model folder it provides.
type ModelMount struct {
	Dataset string // owner/slug as given to Kaggle
	Folder  string // checkpoints, vae, tts, ...
	Subdir  string // path inside the dataset, may be empty
}

// py renders a Go string as a Python literal. JSON is a subset of Python
// literal syntax for strings, which makes this both correct and boring.
func py(s string) string {
	b, err := json.Marshal(s)
	if err != nil {
		return `""`
	}
	return string(b)
}

// datasetDir is where Kaggle mounts a dataset: the slug, lowercased, with the
// owner stripped.
func datasetDir(ref string) string {
	if i := strings.IndexByte(ref, '/'); i >= 0 {
		ref = ref[i+1:]
	}
	return "/kaggle/input/" + strings.ToLower(ref)
}

var notebookTmpl = template.Must(template.New("runner").Funcs(template.FuncMap{
	"py": py, "dir": datasetDir,
}).Parse(`#!/usr/bin/env python3
# Generated by gpuless. Do not edit here - the panel overwrites this on every
# start. This script is pushed as a PRIVATE Kaggle notebook because it carries
# the tunnel token and the panel's shared secret.
import http.server, json, os, shutil, signal, socket, socketserver, subprocess, sys, threading, time, urllib.error, urllib.request

KERNEL_TOKEN = {{ py .KernelToken }}
TUNNEL_TOKEN = {{ py .TunnelToken }}
IDLE_SECONDS = {{ .IdleSeconds }}
CAP_SECONDS  = {{ .CapSeconds }}
RUNTIME_DIR  = {{ py (dir .Runtime) }}
WANTED_GPU   = {{ py .Accelerator }}

COMFY_PORT, EDGE_PORT = 8188, 8189
WORK = "/kaggle/working"
BOOT = time.time()

state = {"last": time.time(), "stop": False, "reason": "", "gpu": "unknown", "comfy": False}
lock = threading.Lock()

def log(*a):
    print("[gpuless]", *a, flush=True)

def touch():
    with lock:
        state["last"] = time.time()

def idle_for():
    with lock:
        return time.time() - state["last"]

# --------------------------------------------------------------- environment

def detect_gpu():
    try:
        import torch
        if torch.cuda.is_available():
            names = [torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())]
            state["gpu"] = ", ".join(names)
            return
    except Exception as e:
        log("torch unavailable:", e)
    state["gpu"] = "none"

def write_model_paths():
    """ComfyUI reads extra model roots from a YAML file, which lets the mounted
    datasets stay read-only exactly where Kaggle put them."""
    lines = ["gpuless:", "  base_path: /kaggle/input/"]
    mounts = {{ .ModelsJSON }}
    for m in mounts:
        root = m["dir"]
        if m["subdir"]:
            root = os.path.join(root, m["subdir"])
        lines.append("  %s: %s" % (m["folder"], root))
    path = os.path.join(WORK, "extra_model_paths.yaml")
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    log("model roots:", path)
    return path

# ------------------------------------------------------------------- ComfyUI

def start_comfy():
    main = os.path.join(RUNTIME_DIR, "ComfyUI", "main.py")
    if not os.path.exists(main):
        raise SystemExit("gpuless: %s is missing - is the runtime dataset attached?" % main)
    for d in ("out", "tmp", "in"):
        os.makedirs(os.path.join(WORK, d), exist_ok=True)

    env = dict(os.environ)
    site = os.path.join(RUNTIME_DIR, "site-packages")
    if os.path.isdir(site):
        env["PYTHONPATH"] = site + os.pathsep + env.get("PYTHONPATH", "")

    cmd = [sys.executable, main,
           "--listen", "127.0.0.1", "--port", str(COMFY_PORT),
           "--output-directory", os.path.join(WORK, "out"),
           "--temp-directory", os.path.join(WORK, "tmp"),
           "--input-directory", os.path.join(WORK, "in"),
           "--extra-model-paths-config", write_model_paths(),
           "--disable-auto-launch"]
    log("starting ComfyUI")
    return subprocess.Popen(cmd, env=env, cwd=os.path.join(RUNTIME_DIR, "ComfyUI"))

def wait_for_port(port, timeout):
    deadline = time.time() + timeout
    while time.time() < deadline:
        with socket.socket() as s:
            s.settimeout(1)
            if s.connect_ex(("127.0.0.1", port)) == 0:
                return True
        time.sleep(1)
    return False

# ---------------------------------------------------------------- cloudflared

def start_tunnel():
    binary = os.path.join(RUNTIME_DIR, "bin", "cloudflared")
    if not os.path.exists(binary):
        binary = shutil.which("cloudflared")
    if not binary:
        raise SystemExit("gpuless: cloudflared not found in the runtime dataset or on PATH")
    os.chmod(binary, 0o755)
    log("starting cloudflared")
    return subprocess.Popen([binary, "tunnel", "--no-autoupdate", "run", "--token", TUNNEL_TOKEN])

# ---------------------------------------------------- edge: auth, control, proxy

class Edge(http.server.BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, *a):
        pass

    def _authorised(self):
        got = self.headers.get("Authorization", "")
        want = "Bearer " + KERNEL_TOKEN
        # The tunnel hostname is public, so every request must carry the
        # shared secret. Length-constant comparison is not worth it here:
        # the token is 256 bits of random and never guessed byte by byte.
        return got == want

    def _send(self, code, body, ctype="application/json"):
        if isinstance(body, (dict, list)):
            body = json.dumps(body).encode()
        elif isinstance(body, str):
            body = body.encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _control(self, path):
        if path == "/gpuless/health":
            self._send(200, {
                "ok": state["comfy"],
                "gpu": state["gpu"],
                "wanted": WANTED_GPU,
                "uptime": int(time.time() - BOOT),
                "idle": int(idle_for()),
                "idle_limit": IDLE_SECONDS,
                "cap": CAP_SECONDS,
            })
            return True
        if path == "/gpuless/shutdown":
            with lock:
                state["stop"], state["reason"] = True, "asked by the panel"
            self._send(200, {"stopping": True})
            return True
        return False

    def _proxy(self, method):
        touch()
        url = "http://127.0.0.1:%d%s" % (COMFY_PORT, self.path)
        length = int(self.headers.get("Content-Length") or 0)
        body = self.rfile.read(length) if length else None
        req = urllib.request.Request(url, data=body, method=method)
        for h in ("Content-Type", "Accept"):
            if self.headers.get(h):
                req.add_header(h, self.headers[h])
        try:
            with urllib.request.urlopen(req, timeout=600) as up:
                payload = up.read()
                self.send_response(up.status)
                ctype = up.headers.get("Content-Type", "application/octet-stream")
                self.send_header("Content-Type", ctype)
                self.send_header("Content-Length", str(len(payload)))
                self.end_headers()
                self.wfile.write(payload)
        except urllib.error.HTTPError as e:
            payload = e.read()
            self.send_response(e.code)
            self.send_header("Content-Type", e.headers.get("Content-Type", "application/json"))
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)
        except Exception as e:
            self._send(502, {"error": "comfyui did not answer: %s" % e})
        finally:
            touch()

    def _handle(self, method):
        if not self._authorised():
            self._send(401, {"error": "unauthorised"})
            return
        if self._control(self.path.split("?")[0]):
            return
        self._proxy(method)

    def do_GET(self):
        self._handle("GET")

    def do_POST(self):
        self._handle("POST")

class Threaded(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True
    allow_reuse_address = True

# ---------------------------------------------------------------------- main

def main():
    detect_gpu()
    log("gpu:", state["gpu"], "(wanted", WANTED_GPU + ")")

    comfy = start_comfy()
    if not wait_for_port(COMFY_PORT, 600):
        raise SystemExit("gpuless: ComfyUI did not come up within 10 minutes")
    state["comfy"] = True
    log("ComfyUI is up")

    edge = Threaded(("127.0.0.1", EDGE_PORT), Edge)
    threading.Thread(target=edge.serve_forever, daemon=True).start()
    log("edge listening on", EDGE_PORT)

    tunnel = start_tunnel()
    touch()

    # Kaggle offers no API to stop a kernel, so the kernel stops itself. The
    # panel only ever asks; these two limits are what actually end the session.
    try:
        while True:
            time.sleep(5)
            if comfy.poll() is not None:
                state["reason"] = "ComfyUI exited with %s" % comfy.returncode
                break
            if tunnel.poll() is not None:
                state["reason"] = "cloudflared exited with %s" % tunnel.returncode
                break
            with lock:
                if state["stop"]:
                    break
            if IDLE_SECONDS > 0 and idle_for() > IDLE_SECONDS:
                state["reason"] = "idle for %ds" % int(idle_for())
                break
            if CAP_SECONDS > 0 and time.time() - BOOT > CAP_SECONDS:
                state["reason"] = "hit the %ds session cap" % CAP_SECONDS
                break
    finally:
        log("stopping:", state["reason"] or "unknown")
        for p in (tunnel, comfy):
            try:
                p.send_signal(signal.SIGTERM)
                p.wait(timeout=20)
            except Exception:
                try:
                    p.kill()
                except Exception:
                    pass
        log("done after %ds" % int(time.time() - BOOT))

main()
`))

// ModelsJSON is rendered into the script as a Python literal list.
func (p NotebookParams) ModelsJSON() string {
	type mount struct {
		Dir    string `json:"dir"`
		Folder string `json:"folder"`
		Subdir string `json:"subdir"`
	}
	out := make([]mount, 0, len(p.Models))
	for _, m := range p.Models {
		out = append(out, mount{Dir: datasetDir(m.Dataset), Folder: m.Folder, Subdir: m.Subdir})
	}
	b, err := json.Marshal(out)
	if err != nil {
		return "[]"
	}
	return string(b)
}

// RenderNotebook produces the runner script pushed to Kaggle.
func RenderNotebook(p NotebookParams) (string, error) {
	var sb strings.Builder
	if err := notebookTmpl.Execute(&sb, p); err != nil {
		return "", fmt.Errorf("render runner: %w", err)
	}
	return sb.String(), nil
}
